# Generated by Django 5.2.3 on 2025-07-15 05:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedWordsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'banned_words',
                'ordering': ('word',),
            },
        ),
        migrations.CreateModel(
            name='CarBrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z0-9- ]{1,49}$', 'Name must start with a capital letter and contain only letters, numbers, spaces, or hyphens (2–50 characters).')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'car_brands',
                'ordering': ('brand',),
            },
        ),
        migrations.CreateModel(
            name='CarModelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='car.carbrandmodel')),
                ('model', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9][A-Za-z0-9- ]{1,49}$', 'Name must contain only letters, numbers, spaces, or hyphens (2–50 characters).')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'car_models',
                'ordering': ('model',),
            },
        ),
        migrations.CreateModel(
            name='CarPosterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car.carbrandmodel')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car.carmodelmodel')),
                ('description', models.TextField()),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999999.99)])),
                ('original_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('UAH', 'Hryvnia')], max_length=3)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_uah', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('exchange_rate_used', models.JSONField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('active', 'Активне'), ('inactive', 'Неактивне')], default='draft', max_length=10)),
                ('edit_attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cars',
                'ordering': ('-id',),
            },
        ),
    ]
