# Generated by Django 5.2.9 on 2025-12-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='carmodelmodel',
            constraint=models.UniqueConstraint(fields=('brand', 'model'), name='unique_model_per_brand'),
        ),
    ]
