# Generated by Django 5.2.1 on 2025-05-27 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrandmodel',
            name='brand',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z0-9- ]{1,49}$', 'Name must start with a capital letter and contain only letters, numbers, spaces, or hyphens (2–50 characters).')]),
        ),
        migrations.AlterField(
            model_name='carmodelmodel',
            name='model',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9- ]{0,50}$', 'Name must contain only letters, numbers, spaces, or hyphens (2–50 characters).')]),
        ),
        migrations.AlterField(
            model_name='carpostermodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999999.99)]),
        ),
    ]
