# Generated by Django 5.2.3 on 2025-06-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_carpostermodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='carpostermodel',
            name='edit_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carpostermodel',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('pending', 'На перевірці'), ('active', 'Активне'), ('inactive', 'Неактивне')], default='pending', max_length=20),
        ),
    ]
