# Generated by Django 5.2.3 on 2025-06-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_bannedword_carpostermodel_edit_attempts_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BannedWord',
            new_name='BannedWordsModel',
        ),
        migrations.AlterModelOptions(
            name='bannedwordsmodel',
            options={'ordering': ('word',)},
        ),
        migrations.AlterModelTable(
            name='bannedwordsmodel',
            table='banned_words',
        ),
    ]
