# Generated by Django 5.2.3 on 2025-07-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_rename_bannedword_bannedwordsmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpostermodel',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('active', 'Активне'), ('inactive', 'Неактивне')], default='draft', max_length=10),
        ),
    ]
