# Generated by Django 5.2.4 on 2025-08-05 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
        ('statistic', '0002_carviewmodel_ip_address_carviewmodel_session_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='carviewmodel',
            index=models.Index(fields=['car', 'user'], name='car_views_car_id_0128d8_idx'),
        ),
        migrations.AddIndex(
            model_name='carviewmodel',
            index=models.Index(fields=['car', 'ip_address'], name='car_views_car_id_9788f7_idx'),
        ),
        migrations.AddIndex(
            model_name='carviewmodel',
            index=models.Index(fields=['car', 'session_key'], name='car_views_car_id_d82a9f_idx'),
        ),
    ]
