# Generated by Django 5.2.9 on 2025-12-13 10:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_carviewmodel_car_views_car_id_0128d8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carviewmodel',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
