# Generated by Django 5.2.1 on 2025-05-27 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_carbrandmodel_brand_alter_carmodelmodel_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodelmodel',
            name='model',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9][A-Za-z0-9- ]{1,49}$', 'Name must contain only letters, numbers, spaces, or hyphens (2–50 characters).')]),
        ),
        migrations.AlterField(
            model_name='carpostermodel',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('UAH', 'Hryvnia')], default='USD', max_length=3),
        ),
    ]
