# Generated by Django 5.2.1 on 2025-05-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_carmodelmodel_model_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbrandmodel',
            options={'ordering': ('brand',)},
        ),
        migrations.AlterModelOptions(
            name='carmodelmodel',
            options={'ordering': ('model',)},
        ),
        migrations.AlterModelOptions(
            name='carpostermodel',
            options={'ordering': ('-id',)},
        ),
    ]
