# Generated by Django 5.2.3 on 2025-07-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelTable(
            name='exchangerate',
            table='exchange_rates',
        ),
    ]
