# Generated by Django 5.2.3 on 2025-06-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usermodel_account_type_usermodel_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='account_type',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('premium', 'Premium')], max_length=10),
        ),
    ]
